# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c
# xcode_project: Example/HDNetworking.xcodebuild
xcode_workspace: Example/HDNetworking.xcworkspace
xcode_scheme: HDNetworking-Example

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild clean -workspace Example/HDNetworking.xcworkspace -scheme HDNetworking-Example | xcpretty
- pod lib lint --allow-warnings
